version: '3.8'

services:
  postgres:
    container_name: tickets_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tickets_api
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    environment:
      IS_LOCAL: true
      DATABASE__USER: postgres
      DATABASE__PASSWORD: postgres
      DATABASE__HOST: postgres
      DATABASE__PORT: 5432
      DATABASE__DB_NAME: postgres
      ACCOUNT_SERVICE__URL: https://jsonplaceholder.typicode.com