"""empty message

Revision ID: 5046525fa816
Revises: 58613b0c444c
Create Date: 2024-08-09 01:18:51.616759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5046525fa816'
down_revision: Union[str, None] = '58613b0c444c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('attendant_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'attendant_name')
    # ### end Alembic commands ###
