name: Quality Checkers
on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:

jobs:
  install-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run_task
        with:
          task: install

  unit-tests:
    needs: ['install-deps']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run_task
        with:
          task: test

  type-check:
    needs: ['install-deps']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run_task
        with:
          task: typecheck

  format-check:
    needs: ['install-deps']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run_task
        with:
          task: fmt-ci

  lint:
    needs: ['install-deps']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run_task
        with:
          task: lint